

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const GET_MYPROJECTS_REQUEST = "GET_MYPROJECTS_REQUEST";
export const GET_MYPROJECTS_SUCCESS = "GET_MYPROJECTS_SUCCESS";
export const GET_MYPROJECTS_FAIL = "GET_MYPROJECTS_FAIL";

export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

export const PROJECT_DELETE_REQUEST = "PROJECT_DELETE_REQUEST";
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS";
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL";

export const PROJECT_EDIT_REQUEST = "PROJECT_EDIT_REQUEST";
export const PROJECT_EDIT_SUCCESS = "PROJECT_EDIT_SUCCESS";
export const PROJECT_EDIT_FAIL = "PROJECT_EDIT_FAIL";


export const GET_PROJECTS_BY_FILTER_REQUEST = "GET_PROJECTS_BY_FILTER_REQUEST";
export const GET_PROJECTS_BY_FILTER_SUCCESS = "GET_PROJECTS_BY_FILTER_SUCCESS";
export const GET_PROJECTS_BY_FILTER_FAIL = "GET_PROJECTS_BY_FILTER_FAIL";

export const GET_MY_PROPOSALS_REQUEST = "GET_MY_PROPOSALS_REQUEST";
export const GET_MY_PROPOSALS_SUCCESS = "GET_MY_PROPOSALS_SUCCESS";
export const GET_MY_PROPOSALS_FAIL = "GET_MY_PROPOSALS_FAIL";

export const FREELANCER_ACTIVE_PROJECTS_REQUEST = "FREELANCER_ACTIVE_PROJECTS_REQUEST";
export const FREELANCER_ACTIVE_PROJECTS_SUCCESS = "FREELANCER_ACTIVE_PROJECTS_SUCCESS";
export const FREELANCER_ACTIVE_PROJECTS_FAIL = "FREELANCER_ACTIVE_PROJECTS_FAIL";

export const FREELANCER_COMPLETED_PROJECTS_REQUEST = "FREELANCER_COMPLETED_PROJECTS_REQUEST";
export const FREELANCER_COMPLETED_PROJECTS_SUCCESS = "FREELANCER_COMPLETED_PROJECTS_SUCCESS";
export const FREELANCER_COMPLETED_PROJECTS_FAIL = "FREELANCER_COMPLETED_PROJECTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";