export const GET_WORKSPACE_REQUEST = "GET_WORKSPACE_REQUEST";
export const GET_WORKSPACE_SUCCESS = "GET_WORKSPACE_SUCCESS";
export const GET_WORKSPACE_FAIL    = "GET_WORKSPACE_FAIL";

export const ADD_MILESTONE_SUCCESS    = "ADD_MILESTONE_SUCCESS";
export const EDIT_MILESTONE_SUCCESS   = "EDIT_MILESTONE_SUCCESS";
export const DELETE_MILESTONE_SUCCESS = "DELETE_MILESTONE_SUCCESS";
export const START_MILESTONE_SUCCESS  = "START_MILESTONE_SUCCESS";
export const SUBMIT_MILESTONE_SUCCESS = "SUBMIT_MILESTONE_SUCCESS";
export const APPROVE_MILESTONE_SUCCESS= "APPROVE_MILESTONE_SUCCESS";
export const REJECT_MILESTONE_SUCCESS = "REJECT_MILESTONE_SUCCESS";

export const COMPLETE_PROJECT_SUCCESS = "COMPLETE_PROJECT_SUCCESS";

export const PAYMENT_INTENT_REQUEST = "PAYMENT_INTENT_REQUEST";
export const PAYMENT_INTENT_SUCCESS = "PAYMENT_INTENT_SUCCESS";
export const PAYMENT_INTENT_FAIL    = "PAYMENT_INTENT_FAIL";
export const PAYMENT_CONFIRM_SUCCESS= "PAYMENT_CONFIRM_SUCCESS";

export const REVIEW_SUCCESS = "REVIEW_SUCCESS";

export const WORKSPACE_ACTION_REQUEST = "WORKSPACE_ACTION_REQUEST";
export const WORKSPACE_ACTION_FAIL    = "WORKSPACE_ACTION_FAIL";
export const CLEAR_WORKSPACE_ERRORS   = "CLEAR_WORKSPACE_ERRORS";

// stats
export const GET_FREELANCER_STATS_REQUEST = "GET_FREELANCER_STATS_REQUEST";
export const GET_FREELANCER_STATS_SUCCESS = "GET_FREELANCER_STATS_SUCCESS";
export const GET_FREELANCER_STATS_FAIL    = "GET_FREELANCER_STATS_FAIL";

export const GET_CLIENT_STATS_REQUEST = "GET_CLIENT_STATS_REQUEST";
export const GET_CLIENT_STATS_SUCCESS = "GET_CLIENT_STATS_SUCCESS";
export const GET_CLIENT_STATS_FAIL    = "GET_CLIENT_STATS_FAIL";